### ISSUE TITLE
Аккуратнее с указателями и статическими массивами

### ISSUE THREAD

**Issue by StriderAJR** [SoraAki000/CppLabs#2]
```c++
int *a = new int[N];
check(a, N);

bool check(int a1[],int N1)
```
Только я тут вижу косячок с типами данных?

**Comment by SoraAki000** [comment]
Это себе для того, чтобы не запутаться

**Comment by StriderAJR** [comment]
@SoraAki000 Уж скорее это сигнал, что вы в принципе можете из-за такого запутаться. Плюс именование переменных должно быть адекватным. В будущем так не делайте, а этот момент нужно поправить.
